### ISSUE TITLE
Use EST instead of local time to determine the default date

### ISSUE THREAD

**Issue by FlyingFoX** [gobanos/cargo-aoc#10]
New puzzles are released at midnight EST, but cargo-aoc defaults to the local date to decide which days  puzzles to operate on.

**Comment by AlisCode** [comment]
Actually, is this mandatory ? In my own use case, I do AoC when I get home. So I'm doing day 8 on day 8 local-time. Makes more sense to use my local timezone. 
Maybe wrap this in a CLAP "--est" or "-e" argument ?

**Comment by FlyingFoX** [comment]
The problem I had with that, is that when I try to do the challenge in my timezone (UTC+1) after midnight it errors out, because it tries to load the challenge of a day that isn't out yet.

I think it would be more intuitive, if `cargo aoc input` got the input for the day of the current challenge as defined by the time the challenge operates in.

**Comment by AlisCode** [comment]
Both approach seem equally intuitive to me. I'll let the choice up to @gobanos to merge this or not, be it in an argument or not :)

**Comment by gobanos** [comment]
Hi !

I agree with @FlyingFoX, the current challenge is what we want to dl by default.
I merged your PR & publish the new version, thanks !
