### ISSUE TITLE
Alpha support for `Result`s

### ISSUE THREAD

**Issue by gobanos** [gobanos/cargo-aoc#12]
Generators & Runners now support `Result`s in return position !
I need some feedback before release, so please install alpha & comment on this issue.

# Setup
In your Cargo.toml:
```
aoc-runner = "0.2.0-alpha1"
aoc-runner-derive = "0.2.0-alpha1"
```
In your terminal:
`$ cargo install cargo-aoc --force --version 0.2.0-alpha1`

# Examples
```
#[aoc_generator(day1)]
fn parse_input(input: &str) -> Result<Vec<i32>, ParseIntError> {
    input
        .lines()
        .map(|l| l.parse())
        .collect()
}

#[aoc(day1, part1)]
fn part1(freqs: &[i32]) -> i32 {
    freqs.iter().sum()
}
```
# Known limitation
By far, the biggest limitation is that I need the return type to be called `Result` (it still can be prefixed with a path), with at least a template parameter.
So these wont work : 
```
type MyRes = Result<Vec<i32>, ParseIntError>;

#[aoc_generator(day1)]
fn parse_input(input: &str) -> MyRes {
    ...
}
```
```
type Result = std::result::Result<Vec<i32>, ParseIntError>;

#[aoc_generator(day1)]
fn parse_input(input: &str) -> MyRes {
    ...
}
```

**Comment by uberjay** [comment]
Oh wow, I was *just* wishing cargo-aoc has this feature. I'll give it a try right now!

**Comment by nugend** [comment]
Could you also support Options?

**Comment by gbear605** [comment]
It's working fine for me!

**Comment by gobanos** [comment]
cargo-aoc 0.2.0, with support for Result & Option is out : https://github.com/gobanos/cargo-aoc/releases/tag/0.2.0
