### ISSUE TITLE
Cannot return `HashMap` from Generator

### ISSUE THREAD

**Issue by belst** [gobanos/cargo-aoc#14]
```
error[E0599]: no method named `as_ref` found for type `std::collections::HashMap<usize, day4::Guard>` in the current scope
  --> src/day4.rs:47:1
   |
47 | #[aoc(day4, part1)]
   | ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

```
#[aoc_generator(day4)]
pub fn gen(input: &str) -> HashMap<usize, Guard> 
```

**Comment by gobanos** [comment]
Hi !
I use [`AsRef`](https://doc.rust-lang.org/std/convert/trait.AsRef.html) as a way to convert owned data (from generator) to ref (for runner), but `AsRef<HashMap>` is not implemented.

A simple workaround is to wrap the `HashMap` in a `Box`, and you can get a `&HashMap` as input for your runner function.

**Comment by TheDan64** [comment]
I also ran into this issue, and similarly I ended up wanting a `&mut HashMap<...>` as input, since sometimes it's nice to be able modify your input data structure.
