### ISSUE TITLE
[Request] Benchmark generator

### ISSUE THREAD

**Issue by iicurtis** [gobanos/cargo-aoc#15]
Would it be possible to benchmark generator functions with Criterion?

It would be useful to compare different parsing methods (logos, regex, nom, pest, etc).

**Comment by gobanos** [comment]
It's a good idea !

I think we should add an CLI parameter for this.

Thanks !

**Comment by gobanos** [comment]
This is done in 0.2.0 : https://github.com/gobanos/cargo-aoc/releases/tag/0.2.0
