### ISSUE TITLE
Support for running in Debug mode

### ISSUE THREAD

**Issue by AlisCode** [gobanos/cargo-aoc#18]
`cargo-aoc`'s autobuild currently compiles the project [using `cargo run --release`](https://github.com/gobanos/cargo-aoc/blob/3f0261a132edbda07b9f93769924133504a1efa8/src/app.rs#L22). 

While this is a cool feature and allows for faster code execution, building in release-mode means we're removing the debug symbols, thus preventing an user to use a debugger such as `LLDB` or `gdb`. 

I think a --debug option in the default `cargo aoc` command is necessary, and would allow the use of a debugger.

Any objection ? Otherwise, I'll implement this and post a PR during the Weekend.

**Comment by gobanos** [comment]
I have already added a `-x` argument to compile with debug symbols. It should be enough to allow usage with `LLDB` or `gdb`. Could you try and report here ?

**Comment by AlisCode** [comment]
Apparently I can't read code :unamused: 

LLDB looking good in VSCode ! :+1: 

![image](https://user-images.githubusercontent.com/12024408/49686892-82068200-fafb-11e8-959c-78278ac8122c.png)

**Comment by gobanos** [comment]
I need to update README.md, and for the name, I tried to keep with the 1 letter name, and `-d` was taken
