### ISSUE TITLE
Allow generator to get untrimmed input

### ISSUE THREAD

**Issue by samueltardieu** [gobanos/cargo-aoc#23]
Hi.

My input for day 13 must not be trimmed as it starts with significant spaces at the beginning of the first line. Is there a way to indicate that the input should not be trimmed for a particular problem?

**Comment by gobanos** [comment]
In aoc-runner 0.2.2, trimming in done only on tailing \n. Update aoc-runner & cargo-aoc

**Comment by samueltardieu** [comment]
Indeed, this works fine now.
