### ISSUE TITLE
Specify a different input file

### ISSUE THREAD

**Issue by samueltardieu** [gobanos/cargo-aoc#25]
It would be great if `cargo aoc` would let us specify an alternate input file. This way, it could be easier to run our code over examples or other people's inputs, for example when assisting them.

**Comment by parbo** [comment]
How do I use this?

**Comment by samueltardieu** [comment]
`cargo aoc -i /tmp/input.txt`, or `cargo aoc -d 22 -i /tmp/input.txt` for example.

**Comment by parbo** [comment]
```
$ cargo aoc -d 3 -p 2 -i input/2018/day3_test.txt
error: Found argument '-i' which wasn't expected, or isn't valid in this context

USAGE:
    cargo-aoc.exe <dummy> -d <day> -p <part>

For more information try --help
```

This doesn't seem to be available in what's on crates.io.
