### ISSUE TITLE
Generated input files aren't found

### ISSUE THREAD

**Issue by gbear605** [gobanos/cargo-aoc#4]
Downloaded input files from `cargo aoc input` are txt files in directories by year (eg. `/input/2017/day1.txt`), but it expects files without an extension and not categorized by year (eg. `/input/day1`). The specific error I'm getting is

    error: couldn't read src/../input/day1: No such file or directory (os error 2)

**Comment by uberjay** [comment]
Yeah, I'm seeing the same thing here...

**Comment by gbear605** [comment]
To add onto the issue, `cargo aoc bench` expects them in the folder by year, like how `cargo aoc input` puts them.

**Comment by gobanos** [comment]
Thanks for reporting !

I have updated `aoc-runner-derive` to v0.1.2, update, and it should work fine !
