### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by samueltardieu** [gobanos/cargo-aoc#41]
Would it be possible to cut a `0.3` release with the current code? Nobody would be forced to upgrade if you think it is not ready, but some of us would really love to use more advanced features (such as the ability to select an alternate input) more easily.

**Comment by gobanos** [comment]
My main concern is with the current codegen compilation (or just check) can take up to 10s when a new symbol is created, and I want to explore different solutions.

I'll try to release with old codegen later today ;)

**Comment by gobanos** [comment]
`0.3` is out, thanks a lot for your support !
