### ISSUE TITLE
E0308 with 0.3.0

### ISSUE THREAD

**Issue by trebinor** [gobanos/cargo-aoc#42]
With `cargo-aoc` 0.3.0 from crates.io, regardless of whether or not `cargo-aoc` 0.2.0 was previously installed, I get the following.  Reproducible for me on CentOS 7 and Windows 10.  Rustc is 1.39.0 for both.  Uninstalling and returning to 0.2.0 fixes it.

> 
> 
> error[E0308]: mismatched types
>   --> src/main.rs:19:44
>    |
> 19 |         match Factory::day9_part1_original(input_day9.clone()) {
>    |                                            ^^^^^^^^^^^^^^^^^^ expected struct `aoc_runner::ArcStr`, found a different
>    |
>    = note: expected type `aoc_runner::ArcStr` (struct `aoc_runner::ArcStr`)
>               found type `aoc_runner::ArcStr` (struct `aoc_runner::ArcStr`)
> note: Perhaps two different versions of crate `aoc_runner` are being used?
>   --> src/main.rs:19:44
>    |
> 19 |         match Factory::day9_part1_original(input_day9.clone()) {
>    |                                            ^^^^^^^^^^^^^^^^^^
> 
> error[E0308]: mismatched types
>   --> src/main.rs:37:44
>    |
> 37 |         match Factory::day9_part2_original(input_day9.clone()) {
>    |                                            ^^^^^^^^^^^^^^^^^^ expected struct `aoc_runner::ArcStr`, found a different
>    |
>    = note: expected type `aoc_runner::ArcStr` (struct `aoc_runner::ArcStr`)
>               found type `aoc_runner::ArcStr` (struct `aoc_runner::ArcStr`)
> note: Perhaps two different versions of crate `aoc_runner` are being used?
>   --> src/main.rs:37:44
>    |
> 37 |         match Factory::day9_part2_original(input_day9.clone()) {
>    |                                            ^^^^^^^^^^^^^^^^^^
> 
> error: aborting due to 2 previous errors
> 
> For more information about this error, try `rustc --explain E0308`.
> error: could not compile `aoc-autobuild`.`

**Comment by gobanos** [comment]
In order to use `cargo-aoc 0.3`, you need `aoc-runner 0.3` and `aoc-runner-derive 0.3`.
