### ISSUE TITLE
An error occurs : entity not found cannot run cargo aoc (2019)

### ISSUE THREAD

**Issue by drmason13** [gobanos/cargo-aoc#46]
```
$ cargo aoc -d 6 -p 1
An error occurs : entity not found
```

I can't work out why I'm getting this error. I was happily using cargo-aoc (on another computer) for the first 5 days. I've started at day 6 on a different laptop but get this error.

There might be something in the files below that I've missed.
It's a bit of a weird & uninformative error and I _think_ it comes from cargo-aoc (Clap) but not 100% sure.
It might be that "missing" days 1-5 causes this - if so is there a way to tell cargo-aoc to skip these days?

<details>
  <summary>lib.rs</summary>

```
use aoc_runner;
use aoc_runner_derive::aoc_lib;

pub mod day6;
pub mod day10;

aoc_lib!{ year = 2019 }
```
</details>

<details>
  <summary>main.rs</summary>

```
use aoc_runner_derive::aoc_main;

fn foo<'a>(input: &'a str) -> &'a str {
    "foo"
}

aoc_main! { lib = advent_of_code_2019 }
```
</details>

<details>
  <summary>Cargo.toml</summary>

```
[package]
name = "advent_of_code_2019"    
version = "0.1.0"
authors = ["David Mason <drmason13@users.noreply.github.com>"]
edition = "2018"
 
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8.2"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
```
</details>

<details>
  <summary>day6.rs</summary>

```
use aoc_runner_derive::{aoc,aoc_generator};
...
#[aoc_generator(day6)]
fn input_generator(input: &str) -> Tree<String> { ... }

#[aoc(day6, part1)]
pub fn solve_part1(orbits: &Tree<String>) -> usize { ... }
```
</details>

Finally, input is definitely there.
```
$ ls input/2019/
day6.txt
```

**Comment by drmason13** [comment]
*Ahem* no issue here. Anyone else running into this issue should run `cargo aoc ...` from the root of your crate and not from within src/ as I was doing!

Quick fix guide
_from within src/ folder_
```
$ rm -rf input/
$ cd ../
$ ls
Cargo.lock  Cargo.toml  src  target
$ cargo aoc input -d 6
Requesting input for year 2019, day 6 ...
$ cargo aoc -d 6 -p 1
...
```

**Comment by tomberek** [comment]
This still seems to occur, even when not running from the root of crate.

**Comment by drmason13** [comment]
Hi, I'm using aoc again this year and it is working well for me.
Did you find a fix for your issue yet? If I was a gambling man I'd bet you've made a mistake like I did (not necessarily the same mistake though!)

**Comment by tomberek** [comment]
Downgraded to 0.2.0.

**Comment by jaysttw** [comment]
> Downgraded to 0.2.0.

Did this work out for you? I'm running Advent of Code on Rust for the first time (and it's also my way of dipping my toes into Rust), and I cannot get this to work.

**Comment by tomberek** [comment]
yes

> > Downgraded to 0.2.0.
> 
> Did this work out for you? I'm running Advent of Code on Rust for the first time (and it's also my way of dipping my toes into Rust), and I cannot get this to work.

**Comment by jaysttw** [comment]
I went back and checked my code again, turns out that I didn't have main.rs or lib.rs. It's otherwise working for me now, on 0.3.

> yes
> 
> > > Downgraded to 0.2.0.
> > 
> > 
> > Did this work out for you? I'm running Advent of Code on Rust for the first time (and it's also my way of dipping my toes into Rust), and I cannot get this to work.

**Comment by tomberek** [comment]
What is main.rs supposed to be?
