### ISSUE TITLE
Include contact info in user agent

### ISSUE THREAD

**Issue by queer-emma** [gobanos/cargo-aoc#88]
The creator of AOC is requesting that tools include contact info in automated requests: https://www.reddit.com/r/adventofcode/comments/z9dhtd/please_include_your_contact_info_in_the_useragent/

**Comment by AlisCode** [comment]
Pull request opened.

This requires a release of the CLI though. Not sure if that's happening.

**Comment by gobanos** [comment]
Version 0.3.3 published, with a custom user agent. Thanks a lot to both of you :blush:
