### ISSUE TITLE
Add a way to run in release mode with `cargo aoc --release`

### ISSUE THREAD

**Issue by St0wy** [gobanos/cargo-aoc#91]
By default `cargo aoc` will run in dev mode, which I don't know how to change.
To me it seems like the only way to run with optimisations is to change the optimisation in for the dev profile in Cargo.toml.

It would be nice to be able to do it like with cargo run by adding `--release` to the command.

**Comment by mwcz** [comment]
It seems to run in release mode for me.

![image](https://user-images.githubusercontent.com/364615/209602399-46d03d21-60f7-4873-b589-4e096cb8f763.png)

It seems to build in dev mode first, then build & run in release mode.

**Comment by St0wy** [comment]
Ah yes didn't notice the second part, my bad
